In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [2]:
X = np.array([[1], [2], [3], [4], [5], [6]])   # X is 2D
y = np.array([2, 4, 6, 8, 10, 12])             # y is 1D
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = LinearRegression()        # hyperparameters are set here, in the constructor
model.fit(X_train, y_train)       # learns from data

print("coef_      :", model.coef_)       # trailing _ = learned after fit
print("intercept_ :", model.intercept_)

coef_      : [2.]
intercept_ : 0.0


In [3]:
y_pred = model.predict(X_test)
print("predictions:", y_pred)
print("actual     :", y_test)
print("R2 score   :", model.score(X_test, y_test))

predictions: [2. 4.]
actual     : [2 4]
R2 score   : 1.0


In [4]:
Xi, yi = load_iris(return_X_y=True)
Xi_train, Xi_test, yi_train, yi_test = train_test_split(Xi, yi, test_size=0.2, random_state=42)

clf = LogisticRegression(max_iter=200)
clf.fit(Xi_train, yi_train)

print("labels       :", clf.predict(Xi_test[:3]))
print("probabilities:\n", clf.predict_proba(Xi_test[:3]))
print("accuracy     :", clf.score(Xi_test, yi_test))

labels       : [1 0 2]
probabilities:
 [[3.80392750e-03 8.27739664e-01 1.68456409e-01]
 [9.46973015e-01 5.30267859e-02 1.98766047e-07]
 [8.86161500e-09 1.54855320e-03 9.98451438e-01]]
accuracy     : 1.0


In [5]:
sc = StandardScaler()
sc.fit(X_train)                           # learns mean and std from train
print("mean_  :", sc.mean_)
print("scale_ :", sc.scale_)

X_train_s = sc.transform(X_train)         # apply
X_test_s = sc.transform(X_test)           # transform only, never fit on test
print("train scaled:", X_train_s.ravel())
print("test scaled :", X_test_s.ravel())

# shortcut for train only
print("fit_transform:", StandardScaler().fit_transform(X_train).ravel())

mean_  : [4.5]
scale_ : [1.11803399]
train scaled: [ 1.34164079 -1.34164079  0.4472136  -0.4472136 ]
test scaled : [-3.13049517 -2.23606798]
fit_transform: [ 1.34164079 -1.34164079  0.4472136  -0.4472136 ]


In [6]:
Xi_train, Xi_test, yi_train, yi_test = train_test_split(Xi, yi, test_size=0.2, random_state=42)

sc = StandardScaler()
Xi_train_s = sc.fit_transform(Xi_train)   # fit on train only
Xi_test_s = sc.transform(Xi_test)         # transform only

clf = LogisticRegression(max_iter=200)
clf.fit(Xi_train_s, yi_train)
print("accuracy:", clf.score(Xi_test_s, yi_test))

accuracy: 1.0


In [7]:
good = StandardScaler().fit(X_train)      # correct: learn from train
bad = StandardScaler().fit(X_test)        # WRONG: learns from test

print("correct:", good.transform(X_test).ravel())
print("WRONG  :", bad.transform(X_test).ravel())

correct: [-3.13049517 -2.23606798]
WRONG  : [-1.  1.]
